config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]
  resources :user_orders, only: [ :index, :create ]
  post '/buy', controller: :sales, action: :create
  delete '/remove_user_order', controller: :user_orders, action: :destroy
  post '/paypal/create/payment',  
    controller: :sales, action: :paypal_create_payment
  post '/paypal/execute/payment',
    controller: :sales, action: :paypal_execute_payment

  get '/checkout', controller: :user_orders, action: :checkout

  namespace :admin do
    resources :users
    root to: "users#index"
  end
  devise_for :users
  resources :users, only: [ :index, :show ]
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  enum status: [ :active, :in_process, :done ]

  default_scope { where(status: :active) }

  belongs_to :user
  belongs_to :product
  has_one :sale

  validates_associated :product

  validates_uniqueness_of :product_id, scope: [:user_id], 
    conditions: -> { where(status: :active) }
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :status, inclusion: { in: statuses.keys }

end

app/controllers/user_orders_controller.rb
class UserOrdersController < ApplicationController
  def index
    product_ids = user_signed_in? ? 
      current_user.orders.map(&:product_id) :
      session[:cart]
    @products = Product.find(product_ids)
  end

  def create
    product = Product.find(secure_params[:product_id])
    if user_signed_in? 
      create_order(product)
    else
      add_to_session_cart(product)
    end
  end

  def destroy
    product_id = secure_params[:product_id].to_i
    if user_signed_in?
      current_user.orders.where(product_id: product_id).limit(1).destroy_all
    else
      session[:cart].delete(product_id) if session[:cart]
    end
    flash_with_redirect(:ok, 'Item was removed from cart.', product_id: product_id)
  rescue ActiveRecord::RecordNotFound
    flash_with_redirect(:error, 'Record not found.', product_id: product_id)
  end

  def checkout
    if user_signed_in? 
      product_ids = current_user.orders.pluck(:product_id)
      @address = current_user.profile.address
      @phone = current_user.profile.phone
      @mobile = current_user.profile.mobile
    else
      product_ids = session[:cart] 
      @address, @phone, @mobile = nil
    end
    @products = Product.where(id: product_ids).limit(product_ids.length)
  end

  private

    def create_order(product)
      order = UserOrder.create( 
        user: current_user,
        product: product,
        amount: 1,
        status: :active
      )
      if order.valid?
        flash_with_redirect(:ok, 'Added to cart')
      else
        flash_with_redirect(:error, "Can't add item to cart", errors: order.errors)
      end
    end
    
    def add_to_session_cart(product)
      (session[:cart] ||= []).push(product.id).uniq!
      flash_with_redirect(:ok, 'Added to cart', product_id: product.id)
    end

    def secure_params
      params.require(:user_order).permit(:product_id)
    end
end

app/helpers/user_orders_helper.rb
module UserOrdersHelper
end

app/views/user_orders/_buy_form.html.haml
- if in_cart
  = link_to 'In cart', user_orders_path, class: 'button success'
- else
  = simple_form_for UserOrder.new do |f|
    =f.hidden_field :product_id, value: product.id 
    =f.button :submit, class: 'success', value: 'Add to cart'

app/views/user_orders/_paypal_button_advanced.html.erb
<script>
  paypal.Button.render({
    env: 'sandbox', // Optional: specify 'sandbox' environment
    payment: function(resolve, reject) {
      var CREATE_PAYMENT_URL = '<%= paypal_create_payment_path  %>';
      return paypal.request.post(CREATE_PAYMENT_URL, 
        { authenticity_token: document.getElementsByName('csrf-token')[0].content,
          'sale[address]': document.getElementById('sale_address').value,
          'sale[phone]':   document.getElementById('sale_phone').value,
          'sale[mobile]':  document.getElementById('sale_mobile').value
        })
        .then(function(data) { resolve(data.paymentID); })
        .catch(function(err) { reject(err); });
    },
    onAuthorize: function(data) {
      // Note: you can display a confirmation page before executing
      var EXECUTE_PAYMENT_URL = '<%= paypal_execute_payment_path %>'
      return paypal.request.post(EXECUTE_PAYMENT_URL,
        { authenticity_token: document.getElementsByName('csrf-token')[0].content,
         paymentID: data.paymentID, payerID: data.payerID })
        .then(function(data) { document.location.href = '<%= root_path %>' })
        .catch(function(err) { document.location.refresh() });
    }
  }, '#paypal-button-advanced');
</script>

app/views/user_orders/_paypal_button_simple.html.erb
<script>
  paypal.Button.render({
    env: 'sandbox',
    client: {
      sandbox: 'AV8FjZdhdtngU-I05lCPAKUyeztLhKv21CFvcMxpQAioYi5ftCJg-zIvfRy2AeElrPkMDC19__Dqccqg'
    },

    commit: true,

    payment: function() {
      // Make a client-side call to the REST api to create the payment

      return paypal.rest.payment.create(this.props.env, this.props.client, {
        transactions: [{
        amount: { total: '<%= total %>', currency: 'USD' }
        }]
      });
    },
    onAuthorize: function(data, actions) {
      return actions.payment.execute().then(function() {
        document.querySelector('#paypal-button-simple-container').innerText = 'Payment Complete!';
      });
    }
  }, '#paypal-button-simple');
</script>

app/views/user_orders/checkout.html.haml
- if @products.blank? 
  %p Cart is empty.
- else
  =javascript_include_tag "https://www.paypalobjects.com/api/checkout.js"
  .row
    .column.large-8
      =simple_form_for Sale.new, url: buy_path do |f|
        =f.input :address, value: @address
        =f.input :phone, value: @phone
        =f.input :mobile, value: @mobile
        =f.button :submit, class: 'button success', value: 'Buy'
    .column.large-4.callout#cart-summary
      - @products.each do |p|
        .row
          .column.large-3
            =image_tag p.images.first.file.small.url
          .column.large-9
            =link_to p.title, p
        .row
          .float-right= "#{p.price} $"
      %hr
      .row#checkout-sum
        .float-left Total:
        .float-right= "#{@products.pluck(:price).sum} $"
      %hr
      #paypal-button-simple-container
        #paypal-button-simple
      =render 'paypal_button_simple', total: "#{@products.pluck(:price).sum}"
      %hr
      #paypal-button-advanced-container
        #paypal-button-advanced
      =render 'paypal_button_advanced'

app/views/user_orders/index.html.haml
.row#cart
  .column.large-12.cart-summary
    - @products.each do |p|
      .row.product-summary
        .columns.large-1
          =simple_form_for UserOrder.new, url: remove_user_order_path, method: :delete do |f|
            =f.hidden_field :product_id, value: p.id
            =f.button :submit, value: 'X'
        .columns.large-2
          =link_to p do
            =image_tag p.images.first.file.small.url, alt: p.title
        .columns.large-6
          =link_to p.title, p
        .columns.large-3
          %p= "#{p.price} $"
      %hr
  .row 
    .column.large-8 
    .column.large-4  
      .callout
        %p= "Total: #{@products.pluck(:price).sum} $"
        =link_to 'Checkout', checkout_path, class: 'button success'