config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]
  resources :user_orders, only: [ :index, :create ]
  post '/buy', controller: :sales, action: :create
  delete '/remove_user_order', controller: :user_orders, action: :destroy
  post '/paypal/create/payment',  
    controller: :sales, action: :paypal_create_payment
  post '/paypal/execute/payment',
    controller: :sales, action: :paypal_execute_payment

  get '/checkout', controller: :user_orders, action: :checkout

  namespace :admin do
    resources :users
    root to: "users#index"
  end
  devise_for :users
  resources :users, only: [ :index, :show ]
end

app/views/layouts/_catalogue.html.haml
- cache 'catalogue', expires_in: 1.hour do
  %h3 Catalogue
  - if Category.main.count == 0
    %p Sorry, no categories for now. :(
  - else
    %ul.vertical.dropdown.menu{'data-dropdown-menu': true, id: :catalogue}
      = render partial: 'layouts/category', collection: Category.main.with_children, cached: true

app/views/layouts/_category.html.haml
%li
  =link_to category.title, category
  - unless category.children.empty?
    %ul.dropdown.menu
      = render partial: 'layouts/category', collection: category.children, cache: true

app/views/layouts/_footer.html.erb
            <footer class="row">
            <div class="large-12 columns">
            <hr>
            <div class="row">
            <div class="large-6 columns">
            <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
            <ul class="inline-list right">
            <li>
            <a href="#">Link 1</a>
            </li>
            <li>
            <a href="#">Link 2</a>
            </li>
            <li>
            <a href="#">Link 3</a>
            </li>
            <li>
            <a href="#">Link 4</a>
            </li>
            </ul>
            </div>
            </div>
            </div>
            </footer> 

app/views/layouts/_header.html.haml
%head
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %title= content_for?(:title) ? yield(:title) : 'Shop'
  %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Shop'}"}
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  = csrf_meta_tags

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_nav_links_for_auth.html.haml
%ul.menu
  - if user_signed_in?
    %li= link_to 'Edit account', edit_user_registration_path
    %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
  - else
    %li= link_to 'Sign in', new_user_session_path
    %li= link_to 'Sign up', new_user_registration_path

  - if user_signed_in?
    -if current_user.try(:admin?)
      %li= link_to 'Admin', '/admin'
      %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
.top-bar
  .top-bar-left
    %ul.menu
      %li= link_to 'Shop', root_path
  .top-bar-right
    = render 'layouts/nav_links_for_auth'
  - if content_for? :top_bar_section
    .top-bar-section
      = render 'layouts/top_bar_section'

app/views/layouts/_top_bar_section.html.haml
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/header'
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .row.clear-both
        .float-right
          = link_to 'In cart: ' + items_in_cart.to_s, user_orders_path, class: 'button success', id: 'in-cart'
      .row
        .large-3.small-9.columns
          = render 'layouts/catalogue'
        .large-9.columns
          = yield
    = render 'layouts/footer'